#!/bin/sh

# Start keybinds (other startup stuff included at the end of file)
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
#bspc rule -a discord
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#############################
##                         ##
##      STARTUP STUFF      ##
##                         ##
#############################

nitrogen --restore &
xrandr -s 1920x1080 -r 144
xsetroot -cursor_name left_ptr
picom --experimental-backend &
discord --start-minimized &
xinput --set-prop 8 'libinput Accel Speed' -0.5 &
polychromatic-cli -v &
$HOME/.config/polybar/launch.sh

# display timeout
xset s off &
xset dpms 1800 1800 1800 & # 1800 secs = 30 mins
xautolock -time 30 -locker slock -notify 30 &

# enable numlock
numlockx &

# run steam
steam -silent &





###  [ OTHER (Unused) ]  ###
#lxsession &
#imwheel &
#setxkbmap us &
